#!/usr/bin/env node
import { readFile, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { resolve } from 'node:path';

const require = createRequire(import.meta.url);
const checker = require('license-checker');

const THIRD_PARTY_START = '<!-- THIRD-PARTY-START -->';
const THIRD_PARTY_END = '<!-- THIRD-PARTY-END -->';

const rootDir = process.cwd();
const packageJsonPath = resolve(rootDir, 'package.json');
const readmePath = resolve(rootDir, 'README.md');
const noticesPath = resolve(rootDir, 'THIRD-PARTY-NOTICES.md');
const isCheckMode = process.argv.includes('--check');

function splitPackageKey(key) {
  const at = key.lastIndexOf('@');
  if (at <= 0) {
    return { name: key, version: 'unknown' };
  }

  return {
    name: key.slice(0, at),
    version: key.slice(at + 1),
  };
}

function toLicenseLabel(licenses) {
  if (Array.isArray(licenses)) {
    return licenses.join(' OR ');
  }

  return String(licenses ?? 'UNKNOWN');
}

async function readLicenseText(path) {
  if (!path) {
    return 'License text not found in package metadata.';
  }

  try {
    return await readFile(path, 'utf8');
  } catch {
    return `License text not found at: ${path}`;
  }
}

function formatRepositoryUrl(repository) {
  if (typeof repository !== 'string' || repository.length === 0) {
    return 'N/A';
  }

  if (repository.startsWith('git+')) {
    return repository.slice(4);
  }

  if (repository.startsWith('git://')) {
    return `https://${repository.slice(6).replace(/\.git$/, '')}`;
  }

  return repository.replace(/\.git$/, '');
}

function injectReadmeSection(readme, section) {
  const start = readme.indexOf(THIRD_PARTY_START);
  const end = readme.indexOf(THIRD_PARTY_END);

  if (start >= 0 && end > start) {
    const before = readme.slice(0, start + THIRD_PARTY_START.length);
    const after = readme.slice(end);
    return `${before}\n\n${section}\n\n${after}`;
  }

  const licenseHeader = '\n## License\n';
  const insertAt = readme.indexOf(licenseHeader);
  if (insertAt === -1) {
    throw new Error('Could not find insertion point in README.md. Expected marker comments or a ## License header.');
  }

  const before = readme.slice(0, insertAt);
  const after = readme.slice(insertAt);
  return `${before}${THIRD_PARTY_START}\n\n${section}\n\n${THIRD_PARTY_END}\n${after}`;
}

function generateReadmeSection(directDeps, scanResults) {
  const lines = [
    '## Third-Party Notices',
    '',
    'This project uses the following direct runtime dependencies:',
    '',
    '| Package | License |',
    '|---------|---------|',
  ];

  for (const depName of directDeps) {
    const record = Object.entries(scanResults).find(([key]) => key.startsWith(`${depName}@`));
    const meta = record?.[1] ?? {};
    const license = toLicenseLabel(meta.licenses);
    const repo = formatRepositoryUrl(meta.repository);
    const label = repo === 'N/A' ? `\`${depName}\`` : `[${depName}](${repo})`;
    lines.push(`| ${label} | ${license} |`);
  }

  lines.push('', 'Full license texts are in [THIRD-PARTY-NOTICES.md](THIRD-PARTY-NOTICES.md).');

  return lines.join('\n');
}

async function generateNotices(scanResults, rootPackageKey) {
  const lines = [
    '# Third-Party Notices',
    '',
    'This file is auto-generated by `npm run generate:notices`.',
    '',
    'It includes license information for production dependencies (including transitive packages).',
    '',
  ];

  const entries = Object.entries(scanResults)
    .filter(([key]) => key !== rootPackageKey)
    .sort(([left], [right]) => left.localeCompare(right));
  for (const [key, meta] of entries) {
    const { name, version } = splitPackageKey(key);
    const license = toLicenseLabel(meta.licenses);
    const repository = formatRepositoryUrl(meta.repository);
    const text = await readLicenseText(meta.licenseFile);

    lines.push(`## ${name} (${version})`);
    lines.push('');
    lines.push(`- License: ${license}`);
    lines.push(`- Repository: ${repository}`);
    lines.push('');
    lines.push('```text');
    lines.push(text.trimEnd());
    lines.push('```');
    lines.push('');
  }

  return `${lines.join('\n').trimEnd()}\n`;
}

function runLicenseScan() {
  return new Promise((resolveScan, rejectScan) => {
    checker.init(
      {
        start: rootDir,
        production: true,
        direct: false,
        json: true,
      },
      (error, packages) => {
        if (error) {
          rejectScan(error);
          return;
        }

        resolveScan(packages);
      },
    );
  });
}

async function main() {
  const packageJson = JSON.parse(await readFile(packageJsonPath, 'utf8'));
  const directDeps = Object.keys(packageJson.dependencies ?? {}).sort((a, b) => a.localeCompare(b));
  const readme = await readFile(readmePath, 'utf8');
  const scanResults = await runLicenseScan();
  const rootPackageKey = `${packageJson.name}@${packageJson.version}`;

  const noticesContent = await generateNotices(scanResults, rootPackageKey);
  const readmeSection = generateReadmeSection(directDeps, scanResults);
  const nextReadme = injectReadmeSection(readme, readmeSection);

  if (isCheckMode) {
    const existingNotices = await readFile(noticesPath, 'utf8').catch(() => '');
    const noticesStale = existingNotices !== noticesContent;
    const readmeStale = readme !== nextReadme;

    if (noticesStale || readmeStale) {
      const staleFiles = [
        ...(noticesStale ? ['THIRD-PARTY-NOTICES.md'] : []),
        ...(readmeStale ? ['README.md'] : []),
      ];
      process.stderr.write(`Notices are out of date: ${staleFiles.join(', ')}\nRun: npm run generate:notices\n`);
      process.exit(1);
    }

    process.stdout.write('Notices are up to date.\n');
    return;
  }

  await writeFile(noticesPath, noticesContent, 'utf8');
  await writeFile(readmePath, nextReadme, 'utf8');
  process.stdout.write('Updated THIRD-PARTY-NOTICES.md and README.md.\n');
}

main().catch((error) => {
  process.stderr.write(`Failed to generate notices: ${error.message}\n`);
  process.exit(1);
});
